[package]
name = "discuss-code"
version = "0.1.0"
authors = ["Phippsaurus <philipp.trucksaess@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = "0.6.1"
rusqlite = "0.20.0"
